import type { AppDefinition } from '../types';
import { CalendarApp } from '../components/apps/CalendarApp';
import { CrewRosterApp } from '../components/apps/CrewRosterApp';
import { ModulePlaceholderApp } from '../components/apps/ModulePlaceholderApp';
import { SettingsApp } from '../components/apps/SettingsApp';

export const APP_REGISTRY: Record<string, AppDefinition> = {
	comms: {
		id: 'comms',
		name: 'COMMS',
		shortName: 'Comms',
		subtitle: 'Subspace communications',
		description: 'Manage hailing frequencies, ship-to-ship channels, and Union comm protocols.',
		category: 'Communications',
		badgeCode: 'COM-01',
		icon: 'message',
		defaultSize: { width: 720, height: 520 },
		minSize: { width: 420, height: 320 },
		defaultGridPos: { row: 0, col: 0 },
		component: ModulePlaceholderApp,
	},
	missions: {
		id: 'missions',
		name: 'MISSIONS',
		shortName: 'Missions',
		subtitle: 'Active directives',
		description: 'Review current mission briefs, objectives, and Union operational orders.',
		category: 'Operations',
		badgeCode: 'OPS-01',
		icon: 'scroll',
		defaultSize: { width: 800, height: 560 },
		minSize: { width: 480, height: 360 },
		defaultGridPos: { row: 0, col: 1 },
		component: ModulePlaceholderApp,
	},
	'crew-roster': {
		id: 'crew-roster',
		name: 'CREW ROSTER',
		shortName: 'Crew',
		subtitle: 'Personnel records',
		description: 'Access crew assignments, qualifications, and department rosters.',
		category: 'Records',
		badgeCode: 'REC-01',
		icon: 'users',
		defaultSize: { width: 820, height: 580 },
		minSize: { width: 480, height: 360 },
		defaultGridPos: { row: 1, col: 0 },
		component: CrewRosterApp,
	},
	'ship-status': {
		id: 'ship-status',
		name: 'SHIP STATUS',
		shortName: 'Status',
		subtitle: 'Vessel systems overview',
		description: 'Monitor hull integrity, power distribution, and core ship systems.',
		category: 'Operations',
		badgeCode: 'OPS-02',
		icon: 'shield',
		defaultSize: { width: 780, height: 520 },
		minSize: { width: 480, height: 360 },
		defaultGridPos: { row: 1, col: 1 },
		component: ModulePlaceholderApp,
	},
	navigation: {
		id: 'navigation',
		name: 'NAVIGATION',
		shortName: 'Nav',
		subtitle: 'Course and positioning',
		description: 'Plot courses, review stellar charts, and manage quantum drive operations.',
		category: 'Navigation',
		badgeCode: 'NAV-01',
		icon: 'compass',
		defaultSize: { width: 820, height: 560 },
		minSize: { width: 500, height: 380 },
		defaultGridPos: { row: 2, col: 0 },
		component: ModulePlaceholderApp,
	},
	calendar: {
		id: 'calendar',
		name: 'CALENDAR',
		shortName: 'Calendar',
		subtitle: 'Ship chronology planner',
		description:
			'Browse ship dates by month, simulate forward through chrono cycles, and schedule future events.',
		category: 'Navigation',
		badgeCode: 'NAV-02',
		icon: 'calendar',
		defaultSize: { width: 760, height: 620 },
		minSize: { width: 420, height: 480 },
		defaultGridPos: { row: 2, col: 2 },
		component: CalendarApp,
	},
	science: {
		id: 'science',
		name: 'SCIENCE',
		shortName: 'Science',
		subtitle: 'Sensor analysis',
		description: 'Analyse sensor data, stellar phenomena, and scientific survey results.',
		category: 'Intelligence',
		badgeCode: 'INT-01',
		icon: 'microscope',
		defaultSize: { width: 760, height: 540 },
		minSize: { width: 480, height: 360 },
		defaultGridPos: { row: 2, col: 1 },
		component: ModulePlaceholderApp,
	},
	logs: {
		id: 'logs',
		name: 'LOGS',
		shortName: 'Logs',
		subtitle: 'Ship record archive',
		description: "Browse captain's logs, incident reports, and official ship documentation.",
		category: 'Records',
		badgeCode: 'REC-02',
		icon: 'logs',
		defaultSize: { width: 700, height: 500 },
		minSize: { width: 420, height: 320 },
		defaultGridPos: { row: 3, col: 0 },
		component: ModulePlaceholderApp,
	},
	settings: {
		id: 'settings',
		name: 'SETTINGS',
		shortName: 'Settings',
		subtitle: 'Terminal configuration',
		description: 'Adjust display preferences, alert thresholds, and terminal behaviour.',
		category: 'Administration',
		badgeCode: 'ADM-01',
		icon: 'settings',
		defaultSize: { width: 640, height: 480 },
		minSize: { width: 400, height: 320 },
		defaultGridPos: { row: 3, col: 1 },
		component: SettingsApp,
	},
};

export const APP_LIST: AppDefinition[] = Object.values(APP_REGISTRY);

export function getAppById(appId: string): AppDefinition | undefined {
	return APP_REGISTRY[appId];
}
