import type { DialogueDefinition } from '../types';
import {
	GREET_DEFINITION,
	ASK_WELLBEING_DEFINITION,
	END_CONVERSATION_DEFINITION,
} from './generalDialogue';
import {
	ASK_DUTY_STATUS_DEFINITION,
	ASK_DEPARTMENT_STATUS_DEFINITION,
	ASK_READINESS_DEFINITION,
	ASK_WORKLOAD_DEFINITION,
} from './dutyDialogue';
import {
	PRAISE_DEFINITION,
	CRITICISE_DEFINITION,
	ENCOURAGE_DEFINITION,
	APOLOGISE_DEFINITION,
	ASK_ADVICE_DEFINITION,
	ASK_PROFESSIONAL_OPINION_DEFINITION,
} from './commandDialogue';
import {
	DISCUSS_CONFLICT_DEFINITION,
	EXPRESS_SYMPATHY_DEFINITION,
	EXPRESS_CONGRATULATIONS_DEFINITION,
} from './relationshipDialogue';
import {
	ASK_ABOUT_SPOUSE_DEFINITION,
	ASK_ABOUT_CHILDREN_DEFINITION,
	ASK_ABOUT_FAMILY_DEFINITION,
	ASK_ABOUT_FRIENDS_DEFINITION,
} from './familyDialogue';
import {
	CIVILIAN_TALK_WORK_DEFINITION,
	CIVILIAN_TALK_LIFE_DEFINITION,
} from './civilianDialogue';
import {
	CHILD_TALK_SCHOOL_DEFINITION,
	CHILD_TALK_HOBBIES_DEFINITION,
	CHILD_TALK_FAMILY_DEFINITION,
} from './childDialogue';
import { ASK_ABOUT_PERSON_DEFINITION } from './personnelDialogue';
import {
	WISH_HAPPY_BIRTHDAY_DEFINITION,
	FOLLOW_UP_REASON_DEFINITION,
	FOLLOW_UP_ASSISTANCE_DEFINITION,
	FOLLOW_UP_SUPPORT_DEFINITION,
} from './contextualDialogue';

export const MASTER_DIALOGUE_DEFINITIONS: readonly DialogueDefinition[] = [
	GREET_DEFINITION,
	ASK_WELLBEING_DEFINITION,
	ASK_DUTY_STATUS_DEFINITION,
	ASK_DEPARTMENT_STATUS_DEFINITION,
	ASK_READINESS_DEFINITION,
	ASK_WORKLOAD_DEFINITION,
	PRAISE_DEFINITION,
	CRITICISE_DEFINITION,
	ENCOURAGE_DEFINITION,
	APOLOGISE_DEFINITION,
	ASK_ADVICE_DEFINITION,
	ASK_PROFESSIONAL_OPINION_DEFINITION,
	DISCUSS_CONFLICT_DEFINITION,
	EXPRESS_SYMPATHY_DEFINITION,
	EXPRESS_CONGRATULATIONS_DEFINITION,
	ASK_ABOUT_SPOUSE_DEFINITION,
	ASK_ABOUT_CHILDREN_DEFINITION,
	ASK_ABOUT_FAMILY_DEFINITION,
	ASK_ABOUT_FRIENDS_DEFINITION,
	CIVILIAN_TALK_WORK_DEFINITION,
	CIVILIAN_TALK_LIFE_DEFINITION,
	CHILD_TALK_SCHOOL_DEFINITION,
	CHILD_TALK_HOBBIES_DEFINITION,
	CHILD_TALK_FAMILY_DEFINITION,
	ASK_ABOUT_PERSON_DEFINITION,
	WISH_HAPPY_BIRTHDAY_DEFINITION,
	FOLLOW_UP_REASON_DEFINITION,
	FOLLOW_UP_ASSISTANCE_DEFINITION,
	FOLLOW_UP_SUPPORT_DEFINITION,
	END_CONVERSATION_DEFINITION,
];

export function getDialogueDefinition(intentId: string): DialogueDefinition | undefined {
	return MASTER_DIALOGUE_DEFINITIONS.find((entry) => entry.intentId === intentId);
}